### ISSUE TITLE
maybe new update broke json

### ISSUE THREAD

**Issue by AngelSigma** [Redmega/bitburner-save-editor#13] opened 2024-11-12 21:05 UTC
upload json empty game or my real game have error (i use emoji in my script but error still in empty game without anything) :
Uncaught (in promise) SyntaxError: Unexpected token 'r', "r ++[  ޭ&"... is not valid JSON
    at JSON.parse (<anonymous>)
    at file.store.ts:75:49
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at br (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:25:9)
(anonymous) @ file.store.ts:75
c @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
br @ asyncToGenerator.js:3
a @ asyncToGenerator.js:25
Promise.then
br @ asyncToGenerator.js:13
a @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
e @ asyncToGenerator.js:21
(anonymous) @ file-loader.tsx:10
He @ react-dom.production.min.js:52
Qe @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
jr @ react-dom.production.min.js:100
Nr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ie @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Mr @ react-dom.production.min.js:105
Zt @ react-dom.production.min.js:75
Jt @ react-dom.production.min.js:74
(anonymous) @ scheduler.production.min.js:18
qo @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73

**Comment by Redmega** [comment] 2024-12-01 00:29
Duplicate of #12

**Closed by Redmega** 2024-12-01 00:29 UTC
